# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `formtastic_i18n` gem.
# Please instead update this file by running `bin/tapioca gem formtastic_i18n`.

module FormtasticI18n; end
class FormtasticI18n::Engine < ::Rails::Engine; end
FormtasticI18n::VERSION = T.let(T.unsafe(nil), String)
